spring.application.name=tasktracker

# localhost postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/tasks-tracker
spring.datasource.username=postgres
spring.datasource.password=comeandgetme
spring.datasource.driver-class-name=org.postgresql.Driver

# Use Hibernate to create the Schema
spring.jpa.hibernate.ddl-auto=update
